import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from './Provider'
import { Roboto } from '@next/font/google';



export const metadata: Metadata = {
  title: "Aman's portfolio",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`"antialiased dark ${roboto.className}`}
        suppressHydrationWarning
      >
       <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
